server:
  # 服务器的HTTP端口，默认为8080
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/thatchedcottage?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

ucode:
  code:
    package-name: "com.thatchedcottage.user"
    domain:
      add-construction-method: true
    join-query: false
    remove-table-prefix: true
    use-swagger: false
    xml:
      add-xml: true
    filter-sys-table: true


# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.thatchedcottage.**.domain
  #配置mapper的扫描，找到所有的mapper.xml映射文件
  #classpath:只能加载找到的第一个资源文件    classpath*:能加载多个路径下的资源文件
  mapperLocations: classpath*:mapper/*.xml
